### PR TITLE
View

### PR DESCRIPTION
**Pull request by Reshman96**
created a Main class to kickoff the application & cleaned up some code

### CODE REVIEW

**Review by cdavii — APPROVED** [review]

**Review by LouisC-H — APPROVED** [review]
🎄

**Review by cdavii — APPROVED** [review]
🦘

**Review by JamesDorling — APPROVED** [review]
Good stuff. Next step is to have control provide the outputs 🦍 👍 😄

**Review by cdavii — APPROVED** [review]

**Comment by JamesDorling** [comment]
Already pulled all of these changes. Seems to be a duplicate pull request.

**Pull request closed without merging**
